# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java
resources:
  repositories:
  - repository: javasample # The name used to reference this repository in the checkout step
    type: github
    endpoint: navya-project
    name: navyabdevops/javasample
  - repository: test # The name used to reference this repository in the checkout step
    type: github
    endpoint: navya-project
    name: navyabdevops/test

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: javasample
- checkout: test

- task: Shellpp@0
  inputs:
    type: 'InlineScript'
    script: 'll'

